#!/bin/sh

cd $(dirname $0)

cd java/efjs
cp ../launchSniffyApplet/jar/*.jar .
cp ../loglet/jar/*.jar .

cd ..
cd ..

cd demo
cd website
cp ../../java/efjs/*.js .
cp ../../java/efjs/*.css .
cp ../../java/efjs/*.jar .
cp ../../php/loglet/*.php .

cd ..
cd ..

cd editor
cd website
cp ../../java/efjs/*.js .
cp ../../java/efjs/*.css .
cp ../../java/efjs/*.jar .
cp ../../php/loglet/*.php .
cp ../../php/editor/*.php .

cd ..
cd ..

cd java
cd efmlWebCompilerModule
cd WebContent
cp ../../../java/efjs/*.js .
cp ../../../java/efjs/*.css .
cp ../../../java/efjs/*.jar .
cp ../../../php/loglet/*.php .
cp ../../../php/editor/*.php .
cp ../../../php/config/*.php .
