#!/bin/sh

cd $(dirname $0)

cd java/efjs
cp ../launchSniffyApplet/jar/*.jar .
cp ../loglet/jar/*.jar .

cd ..
cd ..

cd demo
cd website
cp ../../java/efjs/*.js .
cp ../../java/efjs/*.jar .
cp ../../php/loglet/*.php .

cd ..
cd ..

cd editor
cd website
cp ../../java/efjs/*.js .
cp ../../java/efjs/*.jar .
cp ../../php/loglet/*.php .
cp ../../php/editor/*.php .
